_cfg.crop = {
  [2016] = {
   id = 2016,
   growTime = 60,
   plantIconBundle = 'fruit',
   plantIconName = 'tree',
   harvestIconBundle = 'fruit',
   harvestIconName = 'watermelon ',
   harvest = 3016,
  },
  [2001] = {
   id = 2001,
   growTime = 60,
   plantIconBundle = 'fruit',
   plantIconName = 'tree',
   harvestIconBundle = 'fruit',
   harvestIconName = 'apple',
   harvest = 3001,
  },
  [2002] = {
   id = 2002,
   growTime = 60,
   plantIconBundle = 'fruit',
   plantIconName = 'tree',
   harvestIconBundle = 'fruit',
   harvestIconName = 'bananas',
   harvest = 3002,
  },
  [2003] = {
   id = 2003,
   growTime = 60,
   plantIconBundle = 'fruit',
   plantIconName = 'tree',
   harvestIconBundle = 'fruit',
   harvestIconName = 'blueberry',
   harvest = 3003,
  },
  [2004] = {
   id = 2004,
   growTime = 60,
   plantIconBundle = 'fruit',
   plantIconName = 'tree',
   harvestIconBundle = 'fruit',
   harvestIconName = 'carrot',
   harvest = 3004,
  },
  [2005] = {
   id = 2005,
   growTime = 60,
   plantIconBundle = 'fruit',
   plantIconName = 'tree',
   harvestIconBundle = 'fruit',
   harvestIconName = 'cherry',
   harvest = 3005,
  },
  [2006] = {
   id = 2006,
   growTime = 60,
   plantIconBundle = 'fruit',
   plantIconName = 'tree',
   harvestIconBundle = 'fruit',
   harvestIconName = 'corn',
   harvest = 3006,
  },
  [2007] = {
   id = 2007,
   growTime = 60,
   plantIconBundle = 'fruit',
   plantIconName = 'tree',
   harvestIconBundle = 'fruit',
   harvestIconName = 'eggplant',
   harvest = 3007,
  },
  [2008] = {
   id = 2008,
   growTime = 60,
   plantIconBundle = 'fruit',
   plantIconName = 'tree',
   harvestIconBundle = 'fruit',
   harvestIconName = 'grapes',
   harvest = 3008,
  },
  [2009] = {
   id = 2009,
   growTime = 60,
   plantIconBundle = 'fruit',
   plantIconName = 'tree',
   harvestIconBundle = 'fruit',
   harvestIconName = 'kiwi',
   harvest = 3009,
  },
  [2010] = {
   id = 2010,
   growTime = 60,
   plantIconBundle = 'fruit',
   plantIconName = 'tree',
   harvestIconBundle = 'fruit',
   harvestIconName = 'lemon',
   harvest = 3010,
  },
  [2011] = {
   id = 2011,
   growTime = 60,
   plantIconBundle = 'fruit',
   plantIconName = 'tree',
   harvestIconBundle = 'fruit',
   harvestIconName = 'orange',
   harvest = 3011,
  },
  [2012] = {
   id = 2012,
   growTime = 60,
   plantIconBundle = 'fruit',
   plantIconName = 'tree',
   harvestIconBundle = 'fruit',
   harvestIconName = 'peach',
   harvest = 3012,
  },
  [2013] = {
   id = 2013,
   growTime = 60,
   plantIconBundle = 'fruit',
   plantIconName = 'tree',
   harvestIconBundle = 'fruit',
   harvestIconName = 'pear',
   harvest = 3013,
  },
  [2014] = {
   id = 2014,
   growTime = 60,
   plantIconBundle = 'fruit',
   plantIconName = 'tree',
   harvestIconBundle = 'fruit',
   harvestIconName = 'pineapple',
   harvest = 3014,
  },
  [2015] = {
   id = 2015,
   growTime = 60,
   plantIconBundle = 'fruit',
   plantIconName = 'tree',
   harvestIconBundle = 'fruit',
   harvestIconName = 'pumpiking',
   harvest = 3015,
  },
}
