_cfg.crop = {
  [2016] = {
   id = 2016,
   growTime = 60,
   plantIconBundle = 'fruit',
   plantIconName = 'tree',
   harvestIconBundle = 'fruit',
   harvestIconName = 'watermelon ',
  },
  [2001] = {
   id = 2001,
   growTime = 60,
   plantIconBundle = 'fruit',
   plantIconName = 'tree',
   harvestIconBundle = 'fruit',
   harvestIconName = 'apple',
  },
  [2002] = {
   id = 2002,
   growTime = 60,
   plantIconBundle = 'fruit',
   plantIconName = 'tree',
   harvestIconBundle = 'fruit',
   harvestIconName = 'bananas',
  },
  [2003] = {
   id = 2003,
   growTime = 60,
   plantIconBundle = 'fruit',
   plantIconName = 'tree',
   harvestIconBundle = 'fruit',
   harvestIconName = 'blueberry',
  },
  [2004] = {
   id = 2004,
   growTime = 60,
   plantIconBundle = 'fruit',
   plantIconName = 'tree',
   harvestIconBundle = 'fruit',
   harvestIconName = 'carrot',
  },
  [2005] = {
   id = 2005,
   growTime = 60,
   plantIconBundle = 'fruit',
   plantIconName = 'tree',
   harvestIconBundle = 'fruit',
   harvestIconName = 'cherry',
  },
  [2006] = {
   id = 2006,
   growTime = 60,
   plantIconBundle = 'fruit',
   plantIconName = 'tree',
   harvestIconBundle = 'fruit',
   harvestIconName = 'corn',
  },
  [2007] = {
   id = 2007,
   growTime = 60,
   plantIconBundle = 'fruit',
   plantIconName = 'tree',
   harvestIconBundle = 'fruit',
   harvestIconName = 'eggplant',
  },
  [2008] = {
   id = 2008,
   growTime = 60,
   plantIconBundle = 'fruit',
   plantIconName = 'tree',
   harvestIconBundle = 'fruit',
   harvestIconName = 'grapes',
  },
  [2009] = {
   id = 2009,
   growTime = 60,
   plantIconBundle = 'fruit',
   plantIconName = 'tree',
   harvestIconBundle = 'fruit',
   harvestIconName = 'kiwi',
  },
  [2010] = {
   id = 2010,
   growTime = 60,
   plantIconBundle = 'fruit',
   plantIconName = 'tree',
   harvestIconBundle = 'fruit',
   harvestIconName = 'lemon',
  },
  [2011] = {
   id = 2011,
   growTime = 60,
   plantIconBundle = 'fruit',
   plantIconName = 'tree',
   harvestIconBundle = 'fruit',
   harvestIconName = 'orange',
  },
  [2012] = {
   id = 2012,
   growTime = 60,
   plantIconBundle = 'fruit',
   plantIconName = 'tree',
   harvestIconBundle = 'fruit',
   harvestIconName = 'peach',
  },
  [2013] = {
   id = 2013,
   growTime = 60,
   plantIconBundle = 'fruit',
   plantIconName = 'tree',
   harvestIconBundle = 'fruit',
   harvestIconName = 'pear',
  },
  [2014] = {
   id = 2014,
   growTime = 60,
   plantIconBundle = 'fruit',
   plantIconName = 'tree',
   harvestIconBundle = 'fruit',
   harvestIconName = 'pineapple',
  },
  [2015] = {
   id = 2015,
   growTime = 60,
   plantIconBundle = 'fruit',
   plantIconName = 'tree',
   harvestIconBundle = 'fruit',
   harvestIconName = 'pumpiking',
  },
}
