_cfg.goods = {
  [1] = {
   id = 1,
   assetBundle = 'goods',
   assetName = '1',
   languageId = 10001,
   name = '金币',
   goodsType = 1,
   isBag = 0,
   extraCfg = '',
  },
  [2] = {
   id = 2,
   assetBundle = 'goods',
   assetName = '2',
   languageId = 10002,
   name = '钻石',
   goodsType = 2,
   isBag = 0,
   extraCfg = '',
  },
  [3] = {
   id = 3,
   assetBundle = 'goods',
   assetName = '3',
   languageId = 10003,
   name = '经验',
   goodsType = 3,
   isBag = 1,
   extraCfg = '',
  },
  [1004] = {
   id = 1004,
   assetBundle = 'equip_icon',
   assetName = '1004',
   languageId = 10021,
   name = '裤子',
   goodsType = 1000,
   isBag = 1,
   extraCfg = '_cfg.equip',
  },
  [1005] = {
   id = 1005,
   assetBundle = 'equip_icon',
   assetName = '1005',
   languageId = 10022,
   name = '鞋子',
   goodsType = 1000,
   isBag = 1,
   extraCfg = '_cfg.equip',
  },
  [1006] = {
   id = 1006,
   assetBundle = 'equip_icon',
   assetName = '1006',
   languageId = 10023,
   name = '戒指',
   goodsType = 1000,
   isBag = 1,
   extraCfg = '_cfg.equip',
  },
  [1003] = {
   id = 1003,
   assetBundle = 'equip_icon',
   assetName = '1003',
   languageId = 10020,
   name = '衣服',
   goodsType = 1000,
   isBag = 1,
   extraCfg = '_cfg.equip',
  },
  [3001] = {
   id = 3001,
   assetBundle = 'fruit',
   assetName = 'apple',
   languageId = 0,
   name = '苹果',
   goodsType = 2001,
   isBag = 1,
   extraCfg = '_cfg.crop',
  },
  [3002] = {
   id = 3002,
   assetBundle = 'fruit',
   assetName = 'bananas',
   languageId = 0,
   name = '香蕉',
   goodsType = 2001,
   isBag = 1,
   extraCfg = '_cfg.crop',
  },
  [3003] = {
   id = 3003,
   assetBundle = 'fruit',
   assetName = 'blueberry',
   languageId = 0,
   name = '蓝莓',
   goodsType = 2001,
   isBag = 1,
   extraCfg = '_cfg.crop',
  },
  [3004] = {
   id = 3004,
   assetBundle = 'fruit',
   assetName = 'carrot',
   languageId = 0,
   name = '胡萝卜',
   goodsType = 2001,
   isBag = 1,
   extraCfg = '_cfg.crop',
  },
  [3005] = {
   id = 3005,
   assetBundle = 'fruit',
   assetName = 'cherry',
   languageId = 0,
   name = '樱桃',
   goodsType = 2001,
   isBag = 1,
   extraCfg = '_cfg.crop',
  },
  [3006] = {
   id = 3006,
   assetBundle = 'fruit',
   assetName = 'corn',
   languageId = 0,
   name = '玉米',
   goodsType = 2001,
   isBag = 1,
   extraCfg = '_cfg.crop',
  },
  [3007] = {
   id = 3007,
   assetBundle = 'fruit',
   assetName = 'eggplant',
   languageId = 0,
   name = '茄子',
   goodsType = 2001,
   isBag = 1,
   extraCfg = '_cfg.crop',
  },
  [3008] = {
   id = 3008,
   assetBundle = 'fruit',
   assetName = 'grapes',
   languageId = 0,
   name = '葡萄',
   goodsType = 2001,
   isBag = 1,
   extraCfg = '_cfg.crop',
  },
  [3009] = {
   id = 3009,
   assetBundle = 'fruit',
   assetName = 'kiwi',
   languageId = 0,
   name = '猕猴桃',
   goodsType = 2001,
   isBag = 1,
   extraCfg = '_cfg.crop',
  },
  [3010] = {
   id = 3010,
   assetBundle = 'fruit',
   assetName = 'lemon',
   languageId = 0,
   name = '柠檬',
   goodsType = 2001,
   isBag = 1,
   extraCfg = '_cfg.crop',
  },
  [3011] = {
   id = 3011,
   assetBundle = 'fruit',
   assetName = 'orange',
   languageId = 0,
   name = '橙子',
   goodsType = 2001,
   isBag = 1,
   extraCfg = '_cfg.crop',
  },
  [3012] = {
   id = 3012,
   assetBundle = 'fruit',
   assetName = 'peach',
   languageId = 0,
   name = '桃子',
   goodsType = 2001,
   isBag = 1,
   extraCfg = '_cfg.crop',
  },
  [3013] = {
   id = 3013,
   assetBundle = 'fruit',
   assetName = 'pear',
   languageId = 0,
   name = '雪梨',
   goodsType = 2001,
   isBag = 1,
   extraCfg = '_cfg.crop',
  },
  [3014] = {
   id = 3014,
   assetBundle = 'fruit',
   assetName = 'pineapple',
   languageId = 0,
   name = '菠萝',
   goodsType = 2001,
   isBag = 1,
   extraCfg = '_cfg.crop',
  },
  [3015] = {
   id = 3015,
   assetBundle = 'fruit',
   assetName = 'pumpiking',
   languageId = 0,
   name = '南瓜',
   goodsType = 2001,
   isBag = 1,
   extraCfg = '_cfg.crop',
  },
  [3016] = {
   id = 3016,
   assetBundle = 'fruit',
   assetName = 'watermelon ',
   languageId = 0,
   name = '西瓜',
   goodsType = 2001,
   isBag = 1,
   extraCfg = '_cfg.crop',
  },
  [2001] = {
   id = 2001,
   assetBundle = 'fruit',
   assetName = 'apple',
   languageId = 0,
   name = '苹果种子',
   goodsType = 2000,
   isBag = 1,
   extraCfg = '',
  },
  [2002] = {
   id = 2002,
   assetBundle = 'fruit',
   assetName = 'bananas',
   languageId = 0,
   name = '香蕉种子',
   goodsType = 2000,
   isBag = 1,
   extraCfg = '',
  },
  [2003] = {
   id = 2003,
   assetBundle = 'fruit',
   assetName = 'blueberry',
   languageId = 0,
   name = '蓝莓种子',
   goodsType = 2000,
   isBag = 1,
   extraCfg = '',
  },
  [2004] = {
   id = 2004,
   assetBundle = 'fruit',
   assetName = 'carrot',
   languageId = 0,
   name = '胡萝卜种子',
   goodsType = 2000,
   isBag = 1,
   extraCfg = '',
  },
  [2005] = {
   id = 2005,
   assetBundle = 'fruit',
   assetName = 'cherry',
   languageId = 0,
   name = '樱桃种子',
   goodsType = 2000,
   isBag = 1,
   extraCfg = '',
  },
  [2006] = {
   id = 2006,
   assetBundle = 'fruit',
   assetName = 'corn',
   languageId = 0,
   name = '玉米种子',
   goodsType = 2000,
   isBag = 1,
   extraCfg = '',
  },
  [2007] = {
   id = 2007,
   assetBundle = 'fruit',
   assetName = 'eggplant',
   languageId = 0,
   name = '茄子种子',
   goodsType = 2000,
   isBag = 1,
   extraCfg = '',
  },
  [2008] = {
   id = 2008,
   assetBundle = 'fruit',
   assetName = 'grapes',
   languageId = 0,
   name = '葡萄种子',
   goodsType = 2000,
   isBag = 1,
   extraCfg = '',
  },
  [2009] = {
   id = 2009,
   assetBundle = 'fruit',
   assetName = 'kiwi',
   languageId = 0,
   name = '猕猴桃种子',
   goodsType = 2000,
   isBag = 1,
   extraCfg = '',
  },
  [2010] = {
   id = 2010,
   assetBundle = 'fruit',
   assetName = 'lemon',
   languageId = 0,
   name = '柠檬种子',
   goodsType = 2000,
   isBag = 1,
   extraCfg = '',
  },
  [2011] = {
   id = 2011,
   assetBundle = 'fruit',
   assetName = 'orange',
   languageId = 0,
   name = '橙子种子',
   goodsType = 2000,
   isBag = 1,
   extraCfg = '',
  },
  [2012] = {
   id = 2012,
   assetBundle = 'fruit',
   assetName = 'peach',
   languageId = 0,
   name = '桃子种子',
   goodsType = 2000,
   isBag = 1,
   extraCfg = '',
  },
  [2013] = {
   id = 2013,
   assetBundle = 'fruit',
   assetName = 'pear',
   languageId = 0,
   name = '雪梨种子',
   goodsType = 2000,
   isBag = 1,
   extraCfg = '',
  },
  [2014] = {
   id = 2014,
   assetBundle = 'fruit',
   assetName = 'pineapple',
   languageId = 0,
   name = '菠萝种子',
   goodsType = 2000,
   isBag = 1,
   extraCfg = '',
  },
  [2015] = {
   id = 2015,
   assetBundle = 'fruit',
   assetName = 'pumpiking',
   languageId = 0,
   name = '南瓜种子',
   goodsType = 2000,
   isBag = 1,
   extraCfg = '',
  },
  [2016] = {
   id = 2016,
   assetBundle = 'fruit',
   assetName = 'watermelon ',
   languageId = 0,
   name = '西瓜种子',
   goodsType = 2000,
   isBag = 1,
   extraCfg = '',
  },
  [100] = {
   id = 100,
   assetBundle = 'goods',
   assetName = '100',
   languageId = 10004,
   name = '红糖果',
   goodsType = 100,
   isBag = 1,
   extraCfg = '',
  },
  [101] = {
   id = 101,
   assetBundle = 'goods',
   assetName = '101',
   languageId = 10005,
   name = '橙糖果',
   goodsType = 100,
   isBag = 1,
   extraCfg = '',
  },
  [102] = {
   id = 102,
   assetBundle = 'goods',
   assetName = '102',
   languageId = 10006,
   name = '黄糖果',
   goodsType = 100,
   isBag = 1,
   extraCfg = '',
  },
  [103] = {
   id = 103,
   assetBundle = 'goods',
   assetName = '103',
   languageId = 10007,
   name = '绿糖果',
   goodsType = 100,
   isBag = 1,
   extraCfg = '',
  },
  [104] = {
   id = 104,
   assetBundle = 'goods',
   assetName = '104',
   languageId = 10008,
   name = '青糖果',
   goodsType = 100,
   isBag = 1,
   extraCfg = '',
  },
  [105] = {
   id = 105,
   assetBundle = 'goods',
   assetName = '105',
   languageId = 10009,
   name = '蓝糖果',
   goodsType = 100,
   isBag = 1,
   extraCfg = '',
  },
  [106] = {
   id = 106,
   assetBundle = 'goods',
   assetName = '106',
   languageId = 10010,
   name = '紫糖果',
   goodsType = 100,
   isBag = 1,
   extraCfg = '',
  },
  [107] = {
   id = 107,
   assetBundle = 'goods',
   assetName = '107',
   languageId = 10011,
   name = '红宝石',
   goodsType = 101,
   isBag = 1,
   extraCfg = '',
  },
  [108] = {
   id = 108,
   assetBundle = 'goods',
   assetName = '108',
   languageId = 10012,
   name = '橙宝石',
   goodsType = 101,
   isBag = 1,
   extraCfg = '',
  },
  [109] = {
   id = 109,
   assetBundle = 'goods',
   assetName = '109',
   languageId = 10013,
   name = '黄宝石',
   goodsType = 101,
   isBag = 1,
   extraCfg = '',
  },
  [110] = {
   id = 110,
   assetBundle = 'goods',
   assetName = '110',
   languageId = 10014,
   name = '绿宝石',
   goodsType = 101,
   isBag = 1,
   extraCfg = '',
  },
  [111] = {
   id = 111,
   assetBundle = 'goods',
   assetName = '111',
   languageId = 10015,
   name = '青宝石',
   goodsType = 101,
   isBag = 1,
   extraCfg = '',
  },
  [112] = {
   id = 112,
   assetBundle = 'goods',
   assetName = '112',
   languageId = 10016,
   name = '蓝宝石',
   goodsType = 101,
   isBag = 1,
   extraCfg = '',
  },
  [113] = {
   id = 113,
   assetBundle = 'goods',
   assetName = '113',
   languageId = 10017,
   name = '紫宝石',
   goodsType = 101,
   isBag = 1,
   extraCfg = '',
  },
  [1001] = {
   id = 1001,
   assetBundle = 'equip_icon',
   assetName = '1001',
   languageId = 10018,
   name = '短剑',
   goodsType = 1000,
   isBag = 1,
   extraCfg = '_cfg.equip',
  },
  [1002] = {
   id = 1002,
   assetBundle = 'equip_icon',
   assetName = '1002',
   languageId = 10019,
   name = '头盔',
   goodsType = 1000,
   isBag = 1,
   extraCfg = '_cfg.equip',
  },
}
