_cfg.level = {
  [1] = {
   id = 1,
   main = '普卡村',
   levelNo = 1,
   name = '普卡村1',
   boss = 1,
   monsterLibId = 1,
  },
  [2] = {
   id = 2,
   main = '普卡村',
   levelNo = 2,
   name = '普卡村2',
   boss = 2,
   monsterLibId = 1,
  },
  [3] = {
   id = 3,
   main = '普卡村',
   levelNo = 3,
   name = '普卡村3',
   boss = 3,
   monsterLibId = 1,
  },
  [4] = {
   id = 4,
   main = '普卡村',
   levelNo = 4,
   name = '普卡村4',
   boss = 4,
   monsterLibId = 1,
  },
  [5] = {
   id = 5,
   main = '普卡村',
   levelNo = 5,
   name = '普卡村5',
   boss = 5,
   monsterLibId = 1,
  },
  [6] = {
   id = 6,
   main = '陆南小径',
   levelNo = 1,
   name = '陆南小径1',
   boss = 6,
   monsterLibId = 2,
  },
  [7] = {
   id = 7,
   main = '陆南小径',
   levelNo = 2,
   name = '陆南小径2',
   boss = 7,
   monsterLibId = 2,
  },
  [8] = {
   id = 8,
   main = '陆南小径',
   levelNo = 3,
   name = '陆南小径3',
   boss = 8,
   monsterLibId = 2,
  },
  [9] = {
   id = 9,
   main = '陆南小径',
   levelNo = 4,
   name = '陆南小径4',
   boss = 9,
   monsterLibId = 2,
  },
  [10] = {
   id = 10,
   main = '陆南小径',
   levelNo = 5,
   name = '陆南小径5',
   boss = 10,
   monsterLibId = 2,
  },
  [11] = {
   id = 11,
   main = '农田之地',
   levelNo = 1,
   name = '农田之地1',
   boss = 11,
   monsterLibId = 3,
  },
  [12] = {
   id = 12,
   main = '农田之地',
   levelNo = 2,
   name = '农田之地2',
   boss = 12,
   monsterLibId = 3,
  },
  [13] = {
   id = 13,
   main = '农田之地',
   levelNo = 3,
   name = '农田之地3',
   boss = 13,
   monsterLibId = 3,
  },
  [14] = {
   id = 14,
   main = '农田之地',
   levelNo = 4,
   name = '农田之地4',
   boss = 14,
   monsterLibId = 3,
  },
  [15] = {
   id = 15,
   main = '农田之地',
   levelNo = 5,
   name = '农田之地5',
   boss = 15,
   monsterLibId = 3,
  },
  [16] = {
   id = 16,
   main = '加罗山',
   levelNo = 1,
   name = '加罗山1',
   boss = 16,
   monsterLibId = 4,
  },
  [17] = {
   id = 17,
   main = '加罗山',
   levelNo = 2,
   name = '加罗山2',
   boss = 17,
   monsterLibId = 4,
  },
  [18] = {
   id = 18,
   main = '加罗山',
   levelNo = 3,
   name = '加罗山3',
   boss = 18,
   monsterLibId = 4,
  },
  [19] = {
   id = 19,
   main = '加罗山',
   levelNo = 4,
   name = '加罗山4',
   boss = 19,
   monsterLibId = 4,
  },
  [20] = {
   id = 20,
   main = '加罗山',
   levelNo = 5,
   name = '加罗山5',
   boss = 20,
   monsterLibId = 4,
  },
  [21] = {
   id = 21,
   main = '基布林',
   levelNo = 1,
   name = '基布林1',
   boss = 21,
   monsterLibId = 5,
  },
  [22] = {
   id = 22,
   main = '基布林',
   levelNo = 2,
   name = '基布林2',
   boss = 22,
   monsterLibId = 5,
  },
  [23] = {
   id = 23,
   main = '基布林',
   levelNo = 3,
   name = '基布林3',
   boss = 23,
   monsterLibId = 5,
  },
  [24] = {
   id = 24,
   main = '基布林',
   levelNo = 4,
   name = '基布林4',
   boss = 24,
   monsterLibId = 5,
  },
  [25] = {
   id = 25,
   main = '基布林',
   levelNo = 5,
   name = '基布林5',
   boss = 25,
   monsterLibId = 5,
  },
  [26] = {
   id = 26,
   main = '北郡峭壁',
   levelNo = 1,
   name = '北郡峭壁1',
   boss = 26,
   monsterLibId = 6,
  },
  [27] = {
   id = 27,
   main = '北郡峭壁',
   levelNo = 2,
   name = '北郡峭壁2',
   boss = 27,
   monsterLibId = 6,
  },
  [28] = {
   id = 28,
   main = '北郡峭壁',
   levelNo = 3,
   name = '北郡峭壁3',
   boss = 28,
   monsterLibId = 6,
  },
  [29] = {
   id = 29,
   main = '北郡峭壁',
   levelNo = 4,
   name = '北郡峭壁4',
   boss = 29,
   monsterLibId = 6,
  },
  [30] = {
   id = 30,
   main = '北郡峭壁',
   levelNo = 5,
   name = '北郡峭壁5',
   boss = 30,
   monsterLibId = 6,
  },
  [31] = {
   id = 31,
   main = '尔维丘陵',
   levelNo = 1,
   name = '尔维丘陵1',
   boss = 31,
   monsterLibId = 7,
  },
  [32] = {
   id = 32,
   main = '尔维丘陵',
   levelNo = 2,
   name = '尔维丘陵2',
   boss = 32,
   monsterLibId = 7,
  },
  [33] = {
   id = 33,
   main = '尔维丘陵',
   levelNo = 3,
   name = '尔维丘陵3',
   boss = 33,
   monsterLibId = 7,
  },
  [34] = {
   id = 34,
   main = '尔维丘陵',
   levelNo = 4,
   name = '尔维丘陵4',
   boss = 34,
   monsterLibId = 7,
  },
  [35] = {
   id = 35,
   main = '尔维丘陵',
   levelNo = 5,
   name = '尔维丘陵5',
   boss = 35,
   monsterLibId = 7,
  },
  [36] = {
   id = 36,
   main = '塔贝平原',
   levelNo = 1,
   name = '塔贝平原1',
   boss = 36,
   monsterLibId = 8,
  },
  [37] = {
   id = 37,
   main = '塔贝平原',
   levelNo = 2,
   name = '塔贝平原2',
   boss = 37,
   monsterLibId = 8,
  },
  [38] = {
   id = 38,
   main = '塔贝平原',
   levelNo = 3,
   name = '塔贝平原3',
   boss = 38,
   monsterLibId = 8,
  },
  [39] = {
   id = 39,
   main = '塔贝平原',
   levelNo = 4,
   name = '塔贝平原4',
   boss = 39,
   monsterLibId = 8,
  },
  [40] = {
   id = 40,
   main = '塔贝平原',
   levelNo = 5,
   name = '塔贝平原5',
   boss = 40,
   monsterLibId = 8,
  },
  [41] = {
   id = 41,
   main = '港巴之桥',
   levelNo = 1,
   name = '港巴之桥1',
   boss = 41,
   monsterLibId = 9,
  },
  [42] = {
   id = 42,
   main = '港巴之桥',
   levelNo = 2,
   name = '港巴之桥2',
   boss = 42,
   monsterLibId = 9,
  },
  [43] = {
   id = 43,
   main = '港巴之桥',
   levelNo = 3,
   name = '港巴之桥3',
   boss = 43,
   monsterLibId = 9,
  },
  [44] = {
   id = 44,
   main = '港巴之桥',
   levelNo = 4,
   name = '港巴之桥4',
   boss = 44,
   monsterLibId = 9,
  },
  [45] = {
   id = 45,
   main = '港巴之桥',
   levelNo = 5,
   name = '港巴之桥5',
   boss = 45,
   monsterLibId = 9,
  },
  [46] = {
   id = 46,
   main = '哥龙堡',
   levelNo = 1,
   name = '哥龙堡1',
   boss = 46,
   monsterLibId = 10,
  },
  [47] = {
   id = 47,
   main = '哥龙堡',
   levelNo = 2,
   name = '哥龙堡2',
   boss = 47,
   monsterLibId = 10,
  },
  [48] = {
   id = 48,
   main = '哥龙堡',
   levelNo = 3,
   name = '哥龙堡3',
   boss = 48,
   monsterLibId = 10,
  },
  [49] = {
   id = 49,
   main = '哥龙堡',
   levelNo = 4,
   name = '哥龙堡4',
   boss = 49,
   monsterLibId = 10,
  },
  [50] = {
   id = 50,
   main = '哥龙堡',
   levelNo = 5,
   name = '哥龙堡5',
   boss = 50,
   monsterLibId = 10,
  },
  [51] = {
   id = 51,
   main = '守望林地',
   levelNo = 1,
   name = '守望林地1',
   boss = 51,
   monsterLibId = 11,
  },
  [52] = {
   id = 52,
   main = '守望林地',
   levelNo = 2,
   name = '守望林地2',
   boss = 52,
   monsterLibId = 11,
  },
  [53] = {
   id = 53,
   main = '守望林地',
   levelNo = 3,
   name = '守望林地3',
   boss = 53,
   monsterLibId = 11,
  },
  [54] = {
   id = 54,
   main = '守望林地',
   levelNo = 4,
   name = '守望林地4',
   boss = 54,
   monsterLibId = 11,
  },
  [55] = {
   id = 55,
   main = '守望林地',
   levelNo = 5,
   name = '守望林地5',
   boss = 55,
   monsterLibId = 11,
  },
  [56] = {
   id = 56,
   main = '萨丁石林',
   levelNo = 1,
   name = '萨丁石林1',
   boss = 56,
   monsterLibId = 12,
  },
  [57] = {
   id = 57,
   main = '萨丁石林',
   levelNo = 2,
   name = '萨丁石林2',
   boss = 57,
   monsterLibId = 12,
  },
  [58] = {
   id = 58,
   main = '萨丁石林',
   levelNo = 3,
   name = '萨丁石林3',
   boss = 58,
   monsterLibId = 12,
  },
  [59] = {
   id = 59,
   main = '萨丁石林',
   levelNo = 4,
   name = '萨丁石林4',
   boss = 59,
   monsterLibId = 12,
  },
  [60] = {
   id = 60,
   main = '萨丁石林',
   levelNo = 5,
   name = '萨丁石林5',
   boss = 60,
   monsterLibId = 12,
  },
  [61] = {
   id = 61,
   main = '玛特之脊',
   levelNo = 1,
   name = '玛特之脊1',
   boss = 61,
   monsterLibId = 13,
  },
  [62] = {
   id = 62,
   main = '玛特之脊',
   levelNo = 2,
   name = '玛特之脊2',
   boss = 62,
   monsterLibId = 13,
  },
  [63] = {
   id = 63,
   main = '玛特之脊',
   levelNo = 3,
   name = '玛特之脊3',
   boss = 63,
   monsterLibId = 13,
  },
  [64] = {
   id = 64,
   main = '玛特之脊',
   levelNo = 4,
   name = '玛特之脊4',
   boss = 64,
   monsterLibId = 13,
  },
  [65] = {
   id = 65,
   main = '玛特之脊',
   levelNo = 5,
   name = '玛特之脊5',
   boss = 65,
   monsterLibId = 13,
  },
  [66] = {
   id = 66,
   main = '戈卡沙漠',
   levelNo = 1,
   name = '戈卡沙漠1',
   boss = 66,
   monsterLibId = 14,
  },
  [67] = {
   id = 67,
   main = '戈卡沙漠',
   levelNo = 2,
   name = '戈卡沙漠2',
   boss = 67,
   monsterLibId = 14,
  },
  [68] = {
   id = 68,
   main = '戈卡沙漠',
   levelNo = 3,
   name = '戈卡沙漠3',
   boss = 68,
   monsterLibId = 14,
  },
  [69] = {
   id = 69,
   main = '戈卡沙漠',
   levelNo = 4,
   name = '戈卡沙漠4',
   boss = 69,
   monsterLibId = 14,
  },
  [70] = {
   id = 70,
   main = '戈卡沙漠',
   levelNo = 5,
   name = '戈卡沙漠5',
   boss = 70,
   monsterLibId = 14,
  },
  [71] = {
   id = 71,
   main = '古勒山谷',
   levelNo = 1,
   name = '古勒山谷1',
   boss = 71,
   monsterLibId = 15,
  },
  [72] = {
   id = 72,
   main = '古勒山谷',
   levelNo = 2,
   name = '古勒山谷2',
   boss = 72,
   monsterLibId = 15,
  },
  [73] = {
   id = 73,
   main = '古勒山谷',
   levelNo = 3,
   name = '古勒山谷3',
   boss = 73,
   monsterLibId = 15,
  },
  [74] = {
   id = 74,
   main = '古勒山谷',
   levelNo = 4,
   name = '古勒山谷4',
   boss = 74,
   monsterLibId = 15,
  },
  [75] = {
   id = 75,
   main = '古勒山谷',
   levelNo = 5,
   name = '古勒山谷5',
   boss = 75,
   monsterLibId = 15,
  },
  [76] = {
   id = 76,
   main = '帕宁山脉',
   levelNo = 1,
   name = '帕宁山脉1',
   boss = 76,
   monsterLibId = 16,
  },
  [77] = {
   id = 77,
   main = '帕宁山脉',
   levelNo = 2,
   name = '帕宁山脉2',
   boss = 77,
   monsterLibId = 16,
  },
  [78] = {
   id = 78,
   main = '帕宁山脉',
   levelNo = 3,
   name = '帕宁山脉3',
   boss = 78,
   monsterLibId = 16,
  },
  [79] = {
   id = 79,
   main = '帕宁山脉',
   levelNo = 4,
   name = '帕宁山脉4',
   boss = 79,
   monsterLibId = 16,
  },
  [80] = {
   id = 80,
   main = '帕宁山脉',
   levelNo = 5,
   name = '帕宁山脉5',
   boss = 80,
   monsterLibId = 16,
  },
  [81] = {
   id = 81,
   main = '鲁伊城',
   levelNo = 1,
   name = '鲁伊城1',
   boss = 81,
   monsterLibId = 17,
  },
  [82] = {
   id = 82,
   main = '鲁伊城',
   levelNo = 2,
   name = '鲁伊城2',
   boss = 82,
   monsterLibId = 17,
  },
  [83] = {
   id = 83,
   main = '鲁伊城',
   levelNo = 3,
   name = '鲁伊城3',
   boss = 83,
   monsterLibId = 17,
  },
  [84] = {
   id = 84,
   main = '鲁伊城',
   levelNo = 4,
   name = '鲁伊城4',
   boss = 84,
   monsterLibId = 17,
  },
  [85] = {
   id = 85,
   main = '鲁伊城',
   levelNo = 5,
   name = '鲁伊城5',
   boss = 85,
   monsterLibId = 17,
  },
  [86] = {
   id = 86,
   main = '约纽中心',
   levelNo = 1,
   name = '约纽中心1',
   boss = 86,
   monsterLibId = 18,
  },
  [87] = {
   id = 87,
   main = '约纽中心',
   levelNo = 2,
   name = '约纽中心2',
   boss = 87,
   monsterLibId = 18,
  },
  [88] = {
   id = 88,
   main = '约纽中心',
   levelNo = 3,
   name = '约纽中心3',
   boss = 88,
   monsterLibId = 18,
  },
  [89] = {
   id = 89,
   main = '约纽中心',
   levelNo = 4,
   name = '约纽中心4',
   boss = 89,
   monsterLibId = 18,
  },
  [90] = {
   id = 90,
   main = '约纽中心',
   levelNo = 5,
   name = '约纽中心5',
   boss = 90,
   monsterLibId = 18,
  },
}
